### ISSUE TITLE
missing code at the end

### ISSUE THREAD

**Issue by j2l** [Bogdan-Lyashenko/js-code-to-svg-flowchart#17]
```
return React.createElement(
      ApolloProvider,
      { client: client },
      React.createElement(
MyNews, null)
    );
```
throws something like:

![image](https://user-images.githubusercontent.com/65325/33377724-c5e62404-d512-11e7-9372-beaec5c94f86.png)
without error.

I tested it with online editor and got the same behavior.

**Comment by Bogdan-Lyashenko** [comment]
@j2l, it's not missed, it's hidden because of a long string. And passed objects are parsed specially, that's why you can see ```{*} -> client: client```. If you try it in a browser and hover it with a mouse you will see the title with complete code.
![image](https://user-images.githubusercontent.com/2098309/33382506-38e7c044-d521-11e7-8b6c-b0deca64f474.png)

**Comment by j2l** [comment]
Yeah, I expected to see it visually.
Thanks for the explanation. You're patient :)

**Comment by Bogdan-Lyashenko** [comment]
No worries, happy to help.
